#if !canImport(ObjectiveC)
import XCTest

extension AbstractTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AbstractTestCase = [
        ("testTest", testTest),
    ]
}

extension FileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileTests = [
        ("test_fXz", test_fXz),
        ("testAxiom", testAxiom),
        ("testPUZ001m1", testPUZ001m1),
        ("testPUZ001p1", testPUZ001p1),
        ("testPUZ006m1", testPUZ006m1),
        ("testTest", testTest),
    ]
}

extension ProblemTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProblemTests = [
        ("testPUZ001m1", testPUZ001m1),
        ("testTest", testTest),
    ]
}

extension TermTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TermTests = [
        ("testConstant", testConstant),
        ("testFunction", testFunction),
        ("testPredicate", testPredicate),
        ("testTest", testTest),
        ("testVariable", testVariable),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AbstractTestCase.__allTests__AbstractTestCase),
        testCase(FileTests.__allTests__FileTests),
        testCase(ProblemTests.__allTests__ProblemTests),
        testCase(TermTests.__allTests__TermTests),
    ]
}
#endif
