#if !canImport(ObjectiveC)
import XCTest

extension ATestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ATestCase = [
        ("testTest", testTest),
    ]
}

extension YicesApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__YicesApiTests = [
        ("testDeMorgan", testDeMorgan),
        ("testPfa", testPfa),
        ("testTest", testTest),
    ]
}

extension YicesContextInternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__YicesContextInternalTests = [
        ("testConjunction", testConjunction),
        ("testContradiction", testContradiction),
        ("testDeMorgan", testDeMorgan),
        ("testDisjunction", testDisjunction),
        ("testFunctionCongruence", testFunctionCongruence),
        ("testIdentities", testIdentities),
        ("testMultipleDeclarations", testMultipleDeclarations),
        ("testPfa", testPfa),
        ("testPredicateCongruence", testPredicateCongruence),
        ("testReflexivity", testReflexivity),
        ("testSymmetry", testSymmetry),
        ("testTest", testTest),
        ("testTransitivity", testTransitivity),
    ]
}

extension YicesContextPublicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__YicesContextPublicTests = [
        ("testTest", testTest),
        ("testVersion", testVersion),
    ]
}

extension YicesTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__YicesTestCase = [
        ("testTest", testTest),
    ]
}

extension Z3ApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Z3ApiTests = [
        ("testDeMorgan", testDeMorgan),
        ("testMore", testMore),
        ("testPfa", testPfa),
        ("testTest", testTest),
    ]
}

extension Z3ContextInternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Z3ContextInternalTests = [
        ("testConjunction", testConjunction),
        ("testContradiction", testContradiction),
        ("testDeMorgan", testDeMorgan),
        ("testDisjunction", testDisjunction),
        ("testFunctionCongruence", testFunctionCongruence),
        ("testIdentities", testIdentities),
        ("testMultipleDeclarations", testMultipleDeclarations),
        ("testPfa", testPfa),
        ("testPredicateCongruence", testPredicateCongruence),
        ("testReflexivity", testReflexivity),
        ("testSymmetry", testSymmetry),
        ("testTest", testTest),
        ("testTransitivity", testTransitivity),
    ]
}

extension Z3ContextPublicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Z3ContextPublicTests = [
        ("testTest", testTest),
        ("testVersion", testVersion),
    ]
}

extension Z3TestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Z3TestCase = [
        ("testTest", testTest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ATestCase.__allTests__ATestCase),
        testCase(YicesApiTests.__allTests__YicesApiTests),
        testCase(YicesContextInternalTests.__allTests__YicesContextInternalTests),
        testCase(YicesContextPublicTests.__allTests__YicesContextPublicTests),
        testCase(YicesTestCase.__allTests__YicesTestCase),
        testCase(Z3ApiTests.__allTests__Z3ApiTests),
        testCase(Z3ContextInternalTests.__allTests__Z3ContextInternalTests),
        testCase(Z3ContextPublicTests.__allTests__Z3ContextPublicTests),
        testCase(Z3TestCase.__allTests__Z3TestCase),
    ]
}
#endif
